version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password

  wallet_db:
    build: .
    command: python manage.py migrate
    depends_on:
      - postgres

  wallet_app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - wallet_db