# Generated by Django 5.0.2 on 2024-02-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='wallet.wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='wallet.wallet')),
            ],
        ),
    ]
